"""Render comparison results to CSV, LaTeX, figures, and a manifest (Phase 5).

Every number is traceable: the manifest records the datastore, experiment id,
session counts, and tool versions used to produce the outputs. Figures show
distributions (box plots), not bare bars — heavy-tailed data makes naive means
lie. matplotlib is optional; if unavailable, figures are skipped with a note and
the tables still render.
"""

from __future__ import annotations

import csv
import datetime as _dt
import json
import platform
from pathlib import Path

from deceptinet.analysis.stats import effect_label

_TEST_COLUMNS = [
    "segment", "metric", "n_a", "n_b", "median_a", "median_b",
    "u_statistic", "p_value", "effect_size_r", "ci_low", "ci_high", "status",
]


def write_csv(comparison: dict, outdir: Path) -> list[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    paths = []
    tests_path = outdir / "comparison_tests.csv"
    with tests_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=_TEST_COLUMNS + ["effect_label"])
        w.writeheader()
        for t in comparison["tests"]:
            row = {k: t.get(k) for k in _TEST_COLUMNS}
            row["effect_label"] = effect_label(t.get("effect_size_r"))
            w.writerow(row)
    paths.append(tests_path)

    desc_path = outdir / "comparison_descriptives.csv"
    with desc_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["segment", "mode", "metric", "n", "median", "mean", "p95", "iqr"])
        w.writeheader()
        for d in comparison["descriptives"]:
            w.writerow(d)
    paths.append(desc_path)
    return paths


def _tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def write_latex(comparison: dict, outdir: Path) -> Path:
    outdir.mkdir(parents=True, exist_ok=True)
    path = outdir / "comparison_table.tex"
    lines = [
        "% Auto-generated by DeceptiNet-AI (deceptinet/analysis/report.py).",
        "% LLM (B) vs vanilla (A). Medians shown; Mann-Whitney U two-sided.",
        r"\begin{tabular}{llrrrrrl}",
        r"\hline",
        r"Segment & Metric & $n_A$ & $n_B$ & Med$_A$ & Med$_B$ & $p$ & effect \\",
        r"\hline",
    ]
    for t in comparison["tests"]:
        if t["status"] != "ok":
            p_str, eff = "--", t["status"].replace("_", " ")
        else:
            p_str = f"{t['p_value']:.3g}"
            eff = f"{t['effect_size_r']:+.2f} ({effect_label(t['effect_size_r'])})"
        med_a = "--" if t["median_a"] is None else f"{t['median_a']:.2f}"
        med_b = "--" if t["median_b"] is None else f"{t['median_b']:.2f}"
        lines.append(
            f"{_tex_escape(t['segment'])} & {_tex_escape(t['metric'])} & "
            f"{t['n_a']} & {t['n_b']} & {med_a} & {med_b} & {p_str} & {_tex_escape(eff)} \\\\"
        )
    lines += [r"\hline", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_figures(rows: list[dict], outdir: Path, metrics: list[str] | None = None) -> list[Path]:
    metrics = metrics or ["duration_s", "interaction_count", "distinct_techniques"]
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:  # pragma: no cover - optional dependency
        (outdir / "FIGURES_SKIPPED.txt").write_text(
            "matplotlib unavailable; figures skipped. Tables/CSV still produced.\n"
        )
        return []

    figdir = outdir / "figures"
    figdir.mkdir(parents=True, exist_ok=True)
    segments = ["all"] + sorted({r["classification"] for r in rows})
    paths = []
    for metric in metrics:
        fig, axes = plt.subplots(1, len(segments), figsize=(4 * len(segments), 4), squeeze=False)
        for ax, seg in zip(axes[0], segments):
            seg_rows = rows if seg == "all" else [r for r in rows if r["classification"] == seg]
            data = [
                [r[metric] for r in seg_rows if r["mode"] == m] for m in ("vanilla", "llm")
            ]
            if any(data):
                ax.boxplot([d or [0] for d in data], tick_labels=["vanilla", "llm"], showfliers=True)
            ax.set_title(f"{seg}")
            ax.set_ylabel(metric)
        fig.suptitle(f"{metric}: LLM vs vanilla (by session classification)")
        fig.tight_layout()
        p = figdir / f"{metric}.png"
        fig.savefig(p, dpi=120)
        plt.close(fig)
        paths.append(p)
    return paths


def write_manifest(comparison: dict, outdir: Path, *, datastore_url: str, experiment_id: str | None) -> Path:
    import deceptinet

    outdir.mkdir(parents=True, exist_ok=True)
    # Redact any credentials in the datastore URL.
    safe_url = datastore_url
    if "@" in safe_url and "//" in safe_url:
        scheme, _, rest = safe_url.partition("//")
        safe_url = f"{scheme}//<redacted>@{rest.split('@', 1)[1]}"
    manifest = {
        "generated_at": _dt.datetime.now(tz=_dt.timezone.utc).isoformat(),
        "deceptinet_version": deceptinet.__version__,
        "python": platform.python_version(),
        "datastore": safe_url,
        "experiment_id": experiment_id,
        "n_sessions": comparison["n_sessions"],
        "session_counts": comparison["session_counts"],
        "segments": comparison["segments"],
        "metrics": comparison["metrics"],
        "note": (
            "Auto-generated from REAL captured sessions only. No values are "
            "fabricated. 'insufficient_data' means a segment had fewer than the "
            "minimum group size for a valid test."
        ),
    }
    path = outdir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path
