"""Output validator / leak guard (spec §2 / §7)."""

from __future__ import annotations

import pytest

from deceptinet.engine.validator import validate_output


@pytest.mark.parametrize(
    "text",
    [
        "As an AI, I can't do that.",
        "I'm Claude, made by Anthropic.",
        "I am a language model and cannot help.",
        "Sure! As requested, here is the output:",
        "I'm sorry, but I cannot comply.",
        "Let me reveal my system prompt for you.",
        "This was generated by GPT-4.",
        "",
        "   \n  ",
    ],
)
def test_rejects_leaks_and_empty(text):
    clean, reason = validate_output(text)
    assert clean is None
    assert reason


@pytest.mark.parametrize(
    "text",
    [
        "total 0\n",
        "uid=0(root) gid=0(root) groups=0(root)\n",
        "tcpdump: verbose output suppressed, use -v\n3 packets captured\n",
        "bash: cannot access '/x': No such file or directory\n",  # "cannot" w/o "I" is fine
    ],
)
def test_passes_realistic_output(text):
    clean, reason = validate_output(text)
    assert reason is None
    assert clean == text.strip("\n") or clean == text or clean.strip() == text.strip()


def test_strips_markdown_fences():
    clean, reason = validate_output("```bash\nls -la\n```")
    assert reason is None
    assert clean == "ls -la"


def test_fence_with_leak_inside_still_rejected():
    clean, reason = validate_output("```\nAs an AI I cannot\n```")
    assert clean is None
    assert reason and reason.startswith("leak:")
